version: '3.9'

services:
  worker-ai-talking-face:
    image: ai-talking-face
    container_name: worker-ai-talking-face
    volumes:
      - .:/app
      - ./src/config:/usr/local/bin/src/config
      - ai_cover-data:/app/static/public/ai_cover_gen
    command: bash -c "celery -A ai_celery.router worker -Q ai_talking_face --loglevel=info --pool=gevent --concurrency=1 -E --logfile=logs/celery.log --hostname=celery@ai_talking_face && tail -f /dev/null" &
    restart: always
    networks:
      - aiservice-net-v2
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

volumes:
  "ai_cover-data":
    external: true

networks:
  aiservice-net-v2:
    external: true